### ISSUE TITLE
Is AMD with 2 sockets not supported by ECE?

### ISSUE THREAD

**Issue by pvaldria** [IBM/SpectrumScale_ECE_OS_READINESS#1]
i get this error:

[opc@inst-7xu10-pretty-crappie SpectrumScale_ECE_OS_READINESS]$ sudo ./mor.py --ip 192.168.216.35
[ INFO  ] inst-7xu10-pretty-crappie IBM Spectrum Scale Erasure Code Edition OS readiness version 1.62
[ INFO  ] inst-7xu10-pretty-crappie This tool comes with absolute not warranty
[ INFO  ] inst-7xu10-pretty-crappie Please check https://github.com/IBM/SpectrumScale_ECE_OS_READINESS for details
[ INFO  ] inst-7xu10-pretty-crappie JSON files versions:
[ INFO  ] inst-7xu10-pretty-crappie 	supported OS:		1.5
[ INFO  ] inst-7xu10-pretty-crappie 	packages: 		1.3
[ INFO  ] inst-7xu10-pretty-crappie 	SAS adapters:		1.5
[ INFO  ] inst-7xu10-pretty-crappie 	NIC adapters:		1.0
[ INFO  ] inst-7xu10-pretty-crappie 	HW requirements:	1.4
[ INFO  ] inst-7xu10-pretty-crappie the tool is being run as root
[ INFO  ] inst-7xu10-pretty-crappie checking processor compatibility
[ INFO  ] inst-7xu10-pretty-crappie x86_64 processor is supported to run ECE
[ INFO  ] inst-7xu10-pretty-crappie checking socket count
[ INFO  ] inst-7xu10-pretty-crappie this system is AMD based
[ FATAL ] inst-7xu10-pretty-crappie this system has 2 socket[s] which is not 1 socket[s] required to support ECE
[ INFO  ] inst-7xu10-pretty-crappie checking core count
[ INFO  ] inst-7xu10-pretty-crappie socket 0x0050 has 32 core[s] which complies with 8 cores per socket required to support ECE
[ INFO  ] inst-7xu10-pretty-crappie socket 0x0084 has 32 core[s] which complies with 8 cores per socket required to support ECE

**Comment by bolinches** [comment]
This is not a bug of this tool. for what is whatnot is supported by IBM Spectrum Scale Erasure Code Edition (ECE) Please refer to IBM official documentation and processes to open service requests and/or RFE.

The readme of this tool has a link to the HW requirements document.

Thanks
